### ISSUE TITLE
Errors with TeX Live

### ISSUE THREAD

**Issue by CarLaTeX** [manthanwar/PST-Flags#1]
Hi!
I tried this example:
```
\documentclass{article}
\usepackage{pstricks}
\usepackage{pst-flags}
\begin{document}
	Flag of US: \rput(0,0){\flagUS[2]}
\end{document}
```
on Windows, compiled with pdflatex, with an up-to-date TeX Live distribution, but it gives me errors; see the attached log.
Thanks.
Ciao!
Carla

[pstflags.log](https://github.com/manthanwar/PST-Flags/files/10350022/pstflags.log)

**Comment by manthanwar** [comment]
Ciao Carla,

Please download .sty files and Flags folder and keep them in the root of your TeX path.
https://github.com/manthanwar/PST-Flags/tree/main/pst-flags/tex

Please try with this and let me know.

Also, please send me the errors you get.

Cheerio,
amit

**Comment by CarLaTeX** [comment]
Hi Amit,
I downloaded what you indicated and put them in the path where I have the
.tex file I'm testing.
Is it correct? Is it what you meant with "TeX path"?
I compiled and get the attached log.
Ciao.
Carla

Il giorno gio 5 gen 2023 alle ore 11:07 Amit M. Manthanwar <
***@***.***> ha scritto:

**Comment by manthanwar** [comment]
Hi Carla,

Yes, that is correct. Your tex path is set up correctly.

Create a new tex file say, test.tex and copy the following content

\documentclass{article}
\usepackage{pstricks}
\begin{document}
\pscircle[fillstyle=solid,fillcolor=red](1,1){1}
\end{document}

This should draw a 1 cm circle filled with red color.

If this works then we can say that your tex and pstricks are set up correctly.
Please test this and let me know.

Thanks,
amit

**Comment by CarLaTeX** [comment]
I got an undefined control sequence (see the attached log), so my tex and
pstricks are not set up correctly.
Thanks, Carla

Il giorno ven 6 gen 2023 alle ore 11:01 Amit M. Manthanwar <
***@***.***> ha scritto:

**Comment by CarLaTeX** [comment]
Hi Amit,
I used MiKTeX many years ago, but it gave me a lot of problems.
I moved to TeX Live, and since then it has been working perfectly.
Don't worry, I can do without pst-flags if it means going back to MiKTeX.
Thanks anyway for your kindness.
Ciao.
Carla

Il giorno ven 6 gen 2023 alle ore 13:45 Amit M. Manthanwar <
***@***.***> ha scritto:

**Comment by CarLaTeX** [comment]
Attached the log.
I added \listfiles to show the version of pstricks I'm using.
Thanks,
Carla

Il giorno ven 6 gen 2023 alle ore 19:24 Amit M. Manthanwar
***@***.***> ha scritto:

**Comment by manthanwar** [comment]
Hi Carla, please upload your files at the test repository.

**Comment by manthanwar** [comment]
Hi Carla,

Your line number 4 is wrong
\pscirclefillstyle=solid,fillcolor=red{1}

it should be

\pscircle[fillstyle=solid,fillcolor=red](2,-2){1}

The square brackets are options passed on to \pscircle macro
Number in round brackets (2,2) are the coordinates of the center of the circle.
Number in curly bracket {1} is a radius of circle in centimeter.

Please change the line 4 and try again.

**Comment by manthanwar** [comment]
Try on terminal with manual command line commands

latex test.tex

then run on command line:
dvips test.dvi

finally run on command line:
ps2pdf test.ps

**Comment by manthanwar** [comment]
Also see
https://tex.stackexchange.com/questions/37489/how-can-i-enable-write-18-on-a-miktex-installation

**Comment by CarLaTeX** [comment]
This way, it works.

(In the previous test, I copied the code from the email, it was
different from what there is in the GitHub message).

Ciao.

Il giorno sab 7 gen 2023 alle ore 14:41 Amit M. Manthanwar
***@***.***> ha scritto:

**Comment by manthanwar** [comment]
Hi Carla,

Good news. Now you are able to draw using PSTricks, that is PostScript layer of TeX.
Now you can try other things. Send your email if you have any additional questions. 

Ciao

**Comment by CarLaTeX** [comment]
Thank you, Amit.
pst-flags still doesn't work but don't worry, I added the log on GitHub.
Ciao.


Il giorno sab 7 gen 2023 alle ore 15:25 Amit M. Manthanwar <
***@***.***> ha scritto:

**Comment by manthanwar** [comment]
For toolchain: latex -> dvips -> ps2pdf
You can use automation tool: https://ctan.org/pkg/arara
https://mirror.niser.ac.in/ctan/support/arara/doc/arara-manual.pdf





% arara: latex
% arara: dvips
% arara: ps2pdf: { options : [ -dALLOWPSTRANSPARENCY  -dNOSAFER] }
% arara: clean: { extensions : [ aux, log, dvi, ps ] }
\documentclass{article}
\usepackage{pst-all}
\begin{document}
\section{Draw circle}
\psset{linestyle=solid,linecolor=red,linewidth=1mm,fillstyle=solid,fillcolor=green}
\pscircle(2,-2){1}
\end{document}

**Comment by manthanwar** [comment]
You can use overleaf, a collaborative cloud-based LaTeX editor.
https://www.overleaf.com

Create a collaborative project and share it with the email given in the style file.

**Comment by CarLaTeX** [comment]
This example works both typing the compilation commands in a terminal and
with arara rules.

The example with pst-flags does not work.
Here the link: https://www.overleaf.com/9361688546rqvzddmhbwkk
(of course, in Overleaf it does not work because there is not the package,
since Overleaf is not up-to-date to the latest distribution).

Ciao.

Il giorno sab 7 gen 2023 alle ore 18:27 Amit M. Manthanwar <
***@***.***> ha scritto:

**Comment by manthanwar** [comment]
Done!

**Comment by CarLaTeX** [comment]
In Overleaf I got the same error I got on my pc:
```
! LaTeX Error: Option clash for package xcolor.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.28 \RequirePackage
                    {fp}
The package xcolor has already been loaded with options:
  []
There has now been an attempt to load it with options
  [dvipsnames,svgnames]
Adding the global options:
  ,dvipsnames,svgnames
to your \documentclass declaration may fix this.
Try typing  <return>  to proceed.
```
Look at the log of the shared project.

Sorry, I'm not a developer, just wanted to try pst-flags as an alternative to TikZ: https://tex.stackexchange.com/a/594051/101651, but TikZ is simpler.

By the way, if you are a TeX.SE user, you could add an answer here: https://tex.stackexchange.com/questions/18516/is-there-a-collection-of-national-flags-in-tikz.

Ciao, 
Carla

**Comment by manthanwar** [comment]
I was able to successfully run it.

What your error basically says is, the package xcolor is added multiple times with different options.

For example somewhere it is added with

\usepackage{xcolor}

Therefore, try using the following line in your code 

\usepackage[,dvipsnames,svgnames]{xcolor}

Put this line just before or after \usepackage{pst-flags}

**Comment by manthanwar** [comment]
Also, click menu on overleaf and change setting from pdflatex to latex.

That way you may not need to add xcolor package yourself.

**Comment by CarLaTeX** [comment]
Perfect, thanks! I see you also posted an answer on TeX.SE, great!

**Comment by manthanwar** [comment]
All thanks to you Carla!

**Comment by CarLaTeX** [comment]
Hi Amit,
I'm not so expert as to present pst-flags at a conference (and you are the author, not me).

If you are far from Germany, maybe you could do it with an online presentation, I think they accept online intervention. 

Ciao!
Carla

**Comment by manthanwar** [comment]
Ciao Carla, The package xcolor with options dvipsnames and svgnames was giving that error. Issue is not fixed. Thank you for pointing it out.
